image: Visual Studio 2019

shallow_clone: true

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.RavenDb -c Release 
  - dotnet build Rebus.RavenDb.Tests -c Release 
